languageCode = "zh-cn"
languageName = "简体中文"
displayName = "ZH-CN"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "Cuttontail"
# logo = "img/logo.png"
description = "关注前端和设计，以及那些让我感到惊喜的想法" # 显示在分享后的网站简介里
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "小綿尾巴"
  image = "img/avatar.jpeg"
  # headline = "正在路上的前端工程师"
  bio = "正在路上的前端工程师"
  links = [
    { github = "https://github.com/miawithcodee" },
    { twitter = "https://twitter.com/cuttontailc" },
    { telegram = "https://t.me/cuttontail" },
   ]
