languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Cuttontail"
# logo = "img/logo.png"
description = "front-end developer who writes blog."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "小綿尾巴"
  image = "img/avatar.jpeg"
  # headline = "正在路上的前端工程师"
  bio = "正在路上的前端工程师"
  links = [
    { github = "https://github.com/username" },
    { twitter = "https://twitter.com/username" },
    { telegram = "https://t.me/username" },
   ]
