# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["blog"]
# robots = ""

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog"

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  sharingLinks = false
  showComments = true

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
   apiKey = "AIzaSyCgVSzhtWbaxQSBZzWZks00MgVoSO7aCPA"
   authDomain = "cuttontail.firebaseapp.com"
   projectId = "cuttontail"
   storageBucket = "cuttontail.appspot.com"
   messagingSenderId = "934174669984"
   appId = "1:934174669984:web:d1126405ad4ddd04b81dc5"
   measurementId = "G-Z4CHFZFFYY"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
